version: '3.8'

services:
  yvent-postgres:
    container_name: yvent-container-database
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - yvent-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  server:
    container_name: yvent-application
    restart: unless-stopped
    build: .
    command: npm run dev:concurent
    ports:
      - 3000:3000
    volumes:
      - .:/srv/api:rw
      - /srv/api/node_modules
    working_dir: /srv/api
    env_file:
      - .env
    depends_on:
      - yvent-postgres

  compiler:
    container_name: yvent-compile
    restart: unless-stopped
    build: .
    command: npm run prisma:dev-mode
    volumes:
      - .:/srv/compiler:rw
      - /srv/compiler/node_modules
    working_dir: /srv/compiler
    depends_on:
      - server

volumes:
  yvent-postgres: null
  server: null
