type Booking {
  event: Event!
  price: Float
  refunded: Boolean!
  refundedAt: Date
  user: User!
  uuid: String!
}

type Cursor {
  current: CursorID
  take: Int!
  total: Int!
}

scalar CursorID

scalar Date

type Event {
  bookings: [Booking!]!
  category: EventCategory!
  deletedAt: Date
  description: String
  endDate: Date
  image: String
  nbPlaces: Int!
  participants(
    cursor: CursorID
    page: Int = 1

    """Max 50, Min 1"""
    take: Int = 10
  ): UserConnection!
  participantsCount: Int!
  prices: [Price!]!
  restPlaces: Int!
  startDate: Date!
  title: String!
  uuid: String!
}

type EventCategory {
  isActive: Boolean!
  name: String!
  uuid: String!
}

type EventConnection {
  cursor: Cursor!
  edges: [EventNode!]!
  pageInfo: PageInfo!
}

type EventNode {
  cursor: CursorID!
  node: Event!
}

type File {
  encoding: String!
  filename: String!
  mimetype: String!
}

type Mutation {
  changePassword(newPassword: String!, oldPassword: String!): Boolean!
  createBooking(eventPriceUuid: String!): Booking!
  createEvent(categoryUuid: String!, description: String, endDate: Date, image: Upload, nbPlaces: Int = 0, startDate: Date!, title: String!): Event!
  createEventCategory(name: String!): EventCategory!
  createPrice(amount: Float!, description: String, eventUuid: String!): Price!
  deleteEvent(uuid: String!): Event!
  deleteEventCategories(uuids: [String!]!): [EventCategory!]!
  deleteEventCategory(uuid: String!): EventCategory!
  deletePrice(uuid: String!): Price!
  deleteUser(uuid: String!): User!

  """Pay to join the event"""
  joinEvent(
    """Url to redirect to on cancel"""
    cancelUrl: String!
    eventUuid: String!
    priceUuid: String!

    """Url to redirect to on success"""
    successUrl: String!
  ): String!
  login(email: String!, password: String!): UserAuth!
  refundBooking(bookingUuid: String!): Booking!
  register(displayName: String!, email: String!, password: String!): UserAuth!
  restoreEventCategory(uuid: String!): EventCategory!
  testSub: Boolean!
  testUpload(file: Upload!): String!
  updateEvent(categoryUuid: String, description: String, endDate: Date, nbPlaces: Int = 0, startDate: Date, title: String, uuid: String!): Event!
  updateEventCategory(name: String!, uuid: String!): EventCategory!
  updateUser(displayName: String, email: String, roles: [Role!], uuid: String!): User!
}

type PageInfo {
  currentPage: Int!
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  totalPages: Int!
}

type Price {
  amount: Float!
  description: String!
  uuid: String!
}

type Query {
  event(uuid: String!): Event!
  eventCategories: [EventCategory!]!
  eventParticipants(
    cursor: CursorID
    eventUuid: String!
    page: Int = 1

    """Max 50, Min 1"""
    take: Int = 10
  ): UserConnection!
  events(
    cursor: CursorID
    deleted: Boolean = false
    includePastEvents: Boolean = false
    page: Int = 1

    """Max 50, Min 1"""
    take: Int = 10
  ): EventConnection!
  isAlive: Boolean!
  ping: String!
  user(id: String!): User

  """Get connected user informations"""
  user_infos: User!
  users(
    cursor: CursorID
    page: Int = 1

    """Max 50, Min 1"""
    take: Int = 10
  ): UserConnection!
}

enum Role {
  ADMIN
}

type Subscription {
  eventCreated: User!
  newEvent: Event!
}

type Success {
  success: Boolean!
}

"""The `Upload` scalar type represents a file upload."""
scalar Upload

type User {
  bookings: [Booking!]!
  displayName: String!
  email: String!
  joinedEvents: [Event!]!
  roles: [Role!]!
  uuid: String!
}

type UserAuth {
  jwt: String!
  user: User!
}

type UserConnection {
  cursor: Cursor!
  edges: [UserNode!]!
  pageInfo: PageInfo!
}

type UserNode {
  cursor: CursorID!
  node: User!
}
